/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main.ui;

import main.App;
import main.food.Food;
import main.food.Selection;

/**
 *
 * @author Dongsoo Seo
 */
public class MainFrame extends javax.swing.JFrame {

    private final App app; 

    public MainFrame(App app) {
        this.app = app;
        initComponents();
        init();
    }

    private void init() {
        add(comparisonPanel);
        showSelection(app.getSelection());
        pack();
    }

    private void select(int select) {
        Selection s = app.selectAndShowNext(select);
        if (s == null) {
            showResult(app.showResult());
        } else {
            showSelection(s);
        }
    }

    private void showSelection(Selection s) {
        leftTitleLabel.setText(s.left.name);
        // leftIconLabel.setIcon(s.left.icon);
        rightTitleLabel.setText(s.right.name);
        // rightIconLabel.setIcon(s.right.icon);
    }

    private void showResult(Food result) {
        resultTitleLabel.setText(result.name);
        // resultURLLabel.setText(result.id);
        // resultIconLabel.setIcon(result.icon);
        remove(comparisonPanel);
        add(resultPanel);
        pack();
        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        comparisonPanel = new javax.swing.JPanel();
        leftIconLabel = new javax.swing.JLabel();
        rightIconLabel = new javax.swing.JLabel();
        leftButton = new javax.swing.JButton();
        rightButton = new javax.swing.JButton();
        leftTitleLabel = new javax.swing.JLabel();
        rightTitleLabel = new javax.swing.JLabel();
        resultPanel = new javax.swing.JPanel();
        resultTitleLabel = new javax.swing.JLabel();
        resultURLLabel = new javax.swing.JLabel();
        resultIconLabel = new javax.swing.JLabel();

        leftIconLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        leftIconLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        leftIconLabel.setPreferredSize(new java.awt.Dimension(500, 500));

        rightIconLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rightIconLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        rightIconLabel.setPreferredSize(new java.awt.Dimension(500, 500));

        leftButton.setText("jButton2");
        leftButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leftButtonActionPerformed(evt);
            }
        });

        rightButton.setText("jButton3");
        rightButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rightButtonActionPerformed(evt);
            }
        });

        leftTitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        leftTitleLabel.setText("title");

        rightTitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rightTitleLabel.setText("title");

        javax.swing.GroupLayout comparisonPanelLayout = new javax.swing.GroupLayout(comparisonPanel);
        comparisonPanel.setLayout(comparisonPanelLayout);
        comparisonPanelLayout.setHorizontalGroup(
            comparisonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(comparisonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(comparisonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(leftTitleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(leftIconLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(leftButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(comparisonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rightIconLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rightButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rightTitleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        comparisonPanelLayout.setVerticalGroup(
            comparisonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(comparisonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(comparisonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(leftTitleLabel)
                    .addComponent(rightTitleLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(comparisonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rightIconLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(leftIconLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(comparisonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rightButton)
                    .addComponent(leftButton))
                .addContainerGap())
        );

        resultTitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        resultTitleLabel.setText("title");

        resultURLLabel.setText("url");

        resultIconLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        resultIconLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        resultIconLabel.setPreferredSize(new java.awt.Dimension(500, 500));

        javax.swing.GroupLayout resultPanelLayout = new javax.swing.GroupLayout(resultPanel);
        resultPanel.setLayout(resultPanelLayout);
        resultPanelLayout.setHorizontalGroup(
            resultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(resultPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(resultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(resultTitleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(resultURLLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(resultIconLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        resultPanelLayout.setVerticalGroup(
            resultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(resultPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(resultTitleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(resultURLLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(resultIconLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void leftButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leftButtonActionPerformed
        select(Selection.LEFT);
    }//GEN-LAST:event_leftButtonActionPerformed

    private void rightButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rightButtonActionPerformed
        select(Selection.RIGHT);
    }//GEN-LAST:event_rightButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel comparisonPanel;
    private javax.swing.JButton leftButton;
    private javax.swing.JLabel leftIconLabel;
    private javax.swing.JLabel leftTitleLabel;
    private javax.swing.JLabel resultIconLabel;
    private javax.swing.JPanel resultPanel;
    private javax.swing.JLabel resultTitleLabel;
    private javax.swing.JLabel resultURLLabel;
    private javax.swing.JButton rightButton;
    private javax.swing.JLabel rightIconLabel;
    private javax.swing.JLabel rightTitleLabel;
    // End of variables declaration//GEN-END:variables
}
